# Generated by Django 4.2.28 on 2026-02-17 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the task title (max 200 characters)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed description of the task",
                        null=True,
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Mark as True when task is completed"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when task was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when task was last updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "completed"],
                        name="tasks_task_user_id_f226ed_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="tasks_task_created_5da2cb_idx"
                    ),
                ],
            },
        ),
    ]
